<a href="https://colab.research.google.com/github/Lochipi/DataAnalyticsWithPython/blob/main/DataAnalytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World, this is a practice test for Data Analytics with Numpy and Pandas")

Hello World, this is a practice test for Data Analytics with Numpy and Pandas


Numpy Library

In [ ]:
import numpy as np

Creating a list in numpy

In [ ]:
roll_no = [1,2,3,4]
print(roll_no)

[1, 2, 3, 4]


In [ ]:
arrl = np.array([1,2,3,4])

In [ ]:
print(arrl)

[1 2 3 4]


check the data type of the data.

In [ ]:
type(roll_no)

list

In [ ]:
type(arrl)

numpy.ndarray

Multiply, you will get list repeated

In [ ]:
roll_no * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

Multiplication for array you will get an each multiplied 

In [ ]:
arrl * 3

array([ 3,  6,  9, 12])

In [ ]:
arrl + 10

array([11, 12, 13, 14])

Dimensions of the array

In [ ]:
arrl.ndim

1

4 Items in it, with one dimension

In [ ]:
arrl.shape

(4,)

second array, 2dim array

In [ ]:
arr2 = np.array([[1,2], [3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 2)

Arrange Function

In [ ]:
arr2 = np.arange(1,21)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr3 = np.arange(20, 38, 2)
arr3

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

Indexing 

In [ ]:
arr3[4]

28

Value at last position

you can access the last element using the last number if you know the count. This is not the best case if you have large datasets 

In [ ]:
# if you know the values
arr3[8]

36

Accessing the last index using the best way, down below.

In [ ]:
# nagative indexing
arr3[-1]

36

If you try to access the 9th element you can an error. ☹ 

In [ ]:
arr3[9]

IndexError: ignored

Now, i want to get an

In [ ]:
arr3[7]

34