<a href="https://colab.research.google.com/github/Lochipi/DataAnalyticsWithPython/blob/main/DataAnalytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World, this is a practice test for Data Analytics with Numpy and Pandas")

Hello World, this is a practice test for Data Analytics with Numpy and Pandas


Numpy Library

In [2]:
import numpy as np

Creating a list in numpy

In [3]:
roll_no = [1,2,3,4]
print(roll_no)

[1, 2, 3, 4]


In [4]:
arrl = np.array([1,2,3,4])

In [5]:
print(arrl)

[1 2 3 4]


check the data type of the data.

In [6]:
type(roll_no)

list

In [7]:
type(arrl)

numpy.ndarray

Multiply, you will get list repeated

In [8]:
roll_no * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

Multiplication for array you will get an each multiplied 

In [9]:
arrl * 3

array([ 3,  6,  9, 12])

Adding number to array

In [10]:
arrl + 10

array([11, 12, 13, 14])

Dimensions of the array

In [11]:
arrl.ndim

1

4 Items in it, with one dimension

In [12]:
arrl.shape

(4,)

second array, 2dim array

In [13]:
arr2 = np.array([[1,2], [3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 2)

Arrange Function

In [16]:
arr2 = np.arange(1,21)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
arr3 = np.arange(20, 38, 2)
arr3

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

Indexing 

In [18]:
arr3[4]

28

Value at last position

you can access the last element using the last number if you know the count. This is not the best case if you have large datasets 

In [19]:
# if you know the values
arr3[8]

36

Accessing the last index using the best way, down below.

In [20]:
# nagative indexing
arr3[-1]

36

If you try to access the 9th element you can an error. ☹ 

In [21]:
arr3[9]

IndexError: ignored

In [22]:
m1 = np.arange(20, 38, 2)
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

In [23]:
# getting the 1st/ or 0th element 
m1[0]

20

In [24]:
m1[7]

34

In [25]:
# negative indexing
m1[-2]

34

In [26]:
m1

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

In [27]:
#slicing 
# m1[start_idex : end_indx]  it doesn't inclued the last element.

m1[1:4]

array([22, 24, 26])

In [28]:
m1[ 4 : 8 ]

array([28, 30, 32, 34])

With the negative indexing, the last item starts at -1 coming to the left

In [29]:
m1[ -5 : -1 ]

array([28, 30, 32, 34])

In [30]:
# Fancy Indexing

We're checking if the elements inside m1 are less than 30, it returns true if it below else false.

In [31]:
mask = m1 < 30
mask

array([ True,  True,  True,  True,  True, False, False, False, False])

`m1[mask]` is a way to access certain elements of a NumPy array `m1`. The `mask` is a boolean array of the same shape as `m1`, used to index or filter out certain elements of `m1`

`m1[mask]` will return a new NumPy array of elements from `m1` where the corresponding element in `mask` is `True`

In [32]:
m1[mask]

array([20, 22, 24, 26, 28])

In [33]:
type(m1)

numpy.ndarray

the same can be done this way

In [34]:
m1[ m1 < 30 ]

array([20, 22, 24, 26, 28])

Down below, `m1` is an array variable. `m1%2==0` checks if the elements of the list m1 are even or not. If the element is even (leaves no remainder when divided by 2), then the condition becomes `True`. Otherwise, the condition becomes `False`.

Using square brackets [ ], we apply this condition as a filter on the list m1. It only keeps the numbers that fulfill the condition (i.e., the even numbers), and returns a new list containing only the `even numbers` from the original list m1.

In [35]:
m1[ m1%2 == 0 ]

array([20, 22, 24, 26, 28, 30, 32, 34, 36])

This code creates two one-dimensional numpy arrays- `a` and `b`, with values `[1,3,5]` and `[2,1,1]` respectively. These arrays can be used to perform mathematical operations like addition, subtraction, multiplication, etc. on them.

In [36]:
a = np.array([1,3,5])
b = np.array([2,1,1])

print(a)
print(b)

[1 3 5]
[2 1 1]


Adding the two arrays

In [37]:
a + b

array([3, 4, 6])

finding the smallest value in `a`

In [38]:
np.min(a)

1

Maximum value in `b`

In [39]:
np.max(b)

2

The average of `a`

In [40]:
np.average(a)

3.0

#NPS - NET PROMOTER SCORE

In [73]:
scores = np.loadtxt('survey.txt', dtype='int')
scores

array([ 7, 10,  5, ...,  5,  9, 10])

To check the shape of the scores

In [53]:
scores.shape

(1167,)

The minimum value we use `min()`

In [55]:
scores.min()

1

Max value we use `max()`

In [56]:
scores.max()

10

The mean of the score we use `mean()`

In [57]:
scores.mean()

7.250214224507284

In [66]:
# lets then define detractors and check how we can calculate it. 

`Detractors` they're customers who rate a business, product or service with a score of 0-6 on the Net Promoter Score (NPS) scale. They are typically `unsatisfied customers` who may have had `a negative experience with a business or product`, and are more likely to share their negative feedback with others.

Lets check how many detractors we have.

In [62]:
detractors = scores[(scores < 7 )] 
len(detractors)

332

`Promoters` are customers who rate with a score of `9-10`

In [65]:
promoters = scores[( scores > 8 )]
len(promoters)

609

Calculating the NPS using the formulae above

In [70]:
nps = 100 * ( len(promoters) - len(detractors)) / len(scores)
nps

23.736075407026565

In [71]:
round(nps)

24

# Pandas
Pandas is an `open-source library` for data manipulation and analysis in Python. It is designed to handle and organize large amounts of data in a way that is easy to work with. It provides powerful tools for data cleaning, wrangling, and visualization, making it a popular choice for data scientists and analysts.

In [72]:
import pandas as pd

In [83]:
# data = "/content/data-analyticspracticedata.csv"

df = pd.read_csv("data-analyticspracticedata.csv")
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [79]:
type(df)

pandas.core.frame.DataFrame

In [80]:
df.shape

(1704, 6)

In [81]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

Printing the first 8 elements

In [82]:
df.head(n=8)

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106
5  Afghanistan  1977    14880372      Asia    38.438  786.113360
6  Afghanistan  1982    12881816      Asia    39.854  978.011439
7  Afghanistan  1987    13867957      Asia    40.822  852.395945

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [85]:
df.describe()

year    population     life_exp        gdp_cap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900